server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service #服务名称
  cloud:
    gateway:
       discovery:
         locator:
           enabled: true  #开启从注册中心动态创建路由，利用微服务名进行路由
       routes:
            - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
              #匹配后提供服务的路由地址
              #          uri: http://localhost:8001
              uri: lb://cloud-payment-service
              predicates:
                - Path=/payment/get/** # 断言，路径相匹配的进行路由
                - After=2021-01-25T21:53:50.721+08:00[Asia/Shanghai] #断言，具体时间之后生效
            - id: payment_route2
              #          uri: http://localhost:8001
              uri: lb://cloud-payment-service
              predicates:
                Path=/payment/lb/** #断言,路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#    集群版eureka
#       defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka
#    单机版eureka
       defaultZone: http://localhost:7001/eureka/